// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ai-agents": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ユーザーのAI Agentリストを取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Agent"
                ],
                "summary": "AI Agentリスト取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.AgentsResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新しいAI Agentを作成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Agent"
                ],
                "summary": "AI Agent作成",
                "parameters": [
                    {
                        "description": "AI Agent作成情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.CreateAgentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "作成成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.AgentResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ai-agents/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "IDでAI Agentを取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Agent"
                ],
                "summary": "AI Agent取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AI Agent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.AgentResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "AI Agentが見つかりません",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/conversations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ユーザーの会話一覧を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "会話一覧取得",
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ConversationsListResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "AI Agentとの会話を取得または作成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "会話取得/作成",
                "parameters": [
                    {
                        "description": "AI Agent ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.GetOrCreateConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得/作成成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ConversationResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/conversations/{id}/messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "会話のメッセージ履歴を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "メッセージ履歴取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会話ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "取得件数（デフォルト: 50）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.MessagesResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "会話にメッセージを送信してAI応答を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "メッセージ送信",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会話ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "メッセージ内容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "送信成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/confirm-forgot-password": {
            "post": {
                "description": "確認コードを使って新しいパスワードを設定します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "パスワードリセット確認",
                "parameters": [
                    {
                        "description": "パスワードリセット情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.ConfirmForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "リセット成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/confirm-signup": {
            "post": {
                "description": "メールで送信された確認コードを使ってユーザー登録を確認します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "ユーザー登録確認",
                "parameters": [
                    {
                        "description": "確認コード",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.ConfirmSignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "確認成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/forgot-password": {
            "post": {
                "description": "パスワードリセット用の確認コードをメールで送信します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "パスワードリセット要求",
                "parameters": [
                    {
                        "description": "ユーザー名",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "メール送信成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Cookieからリフレッシュトークンを取得して新しいアクセストークンを発行します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "トークンリフレッシュ",
                "responses": {
                    "200": {
                        "description": "トークンリフレッシュ成功（新しいトークンはCookieに保存）",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.MessageResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "description": "ユーザー名とパスワードでログインします",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "ユーザーログイン",
                "parameters": [
                    {
                        "description": "ログイン情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ログイン成功（トークンはCookieに保存）",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.AuthResultResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signout": {
            "post": {
                "description": "ユーザーをログアウトします（グローバルサインアウト、Cookieをクリア）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "ログアウト",
                "responses": {
                    "200": {
                        "description": "ログアウト成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "新規ユーザーを登録します。登録後に確認コードがメールで送信されます。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "ユーザー登録",
                "parameters": [
                    {
                        "description": "ユーザー登録情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "登録成功（トークンはCookieに保存）",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.AuthResultResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ユーザーの一覧を取得します（ページネーション対応）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "ユーザー一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "取得件数（デフォルト: 10）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "オフセット（デフォルト: 0）",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ユーザー一覧取得成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.UsersResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/email": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みユーザーのメールアドレスを変更します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "メールアドレス変更",
                "parameters": [
                    {
                        "description": "新しいメールアドレス",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.ChangeEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "変更成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.UserResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みユーザーの自分のプロフィールを取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "プロフィール取得",
                "responses": {
                    "200": {
                        "description": "プロフィール取得成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.UserResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証済みユーザーの表示名を更新します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "プロフィール更新",
                "parameters": [
                    {
                        "description": "更新情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_request.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.UserResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定されたIDのユーザー情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "ユーザーをIDで取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ユーザーID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ユーザー取得成功",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.UserResponse"
                        }
                    },
                    "400": {
                        "description": "バリデーションエラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "認証エラー",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "ユーザーが見つかりません",
                        "schema": {
                            "$ref": "#/definitions/backend-go_internal_handler_http_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "backend-go_internal_handler_http_request.ChangeEmailRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_request.ConfirmForgotPasswordRequest": {
            "type": "object",
            "required": [
                "confirmation_code",
                "email",
                "new_password"
            ],
            "properties": {
                "confirmation_code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "backend-go_internal_handler_http_request.ConfirmSignUpRequest": {
            "type": "object",
            "required": [
                "confirmation_code",
                "email"
            ],
            "properties": {
                "confirmation_code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_request.CreateAgentRequest": {
            "type": "object",
            "required": [
                "name",
                "persona_type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "persona_type": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_request.ForgotPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_request.GetOrCreateConversationRequest": {
            "type": "object",
            "required": [
                "ai_agent_id"
            ],
            "properties": {
                "ai_agent_id": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_request.SendMessageRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_request.SignInRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_request.SignUpRequest": {
            "type": "object",
            "required": [
                "display_name",
                "email",
                "password"
            ],
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "backend-go_internal_handler_http_request.UpdateProfileRequest": {
            "type": "object",
            "required": [
                "display_name"
            ],
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        },
        "backend-go_internal_handler_http_response.AgentResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_chat_at": {
                    "type": "string"
                },
                "max_tokens": {
                    "type": "integer"
                },
                "message_count": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "persona_type": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "system_prompt": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                },
                "tools_enabled": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_response.AgentsResponse": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend-go_internal_handler_http_response.AgentResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "backend-go_internal_handler_http_response.AuthResultResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/backend-go_internal_handler_http_response.UserResponse"
                }
            }
        },
        "backend-go_internal_handler_http_response.ConversationResponse": {
            "type": "object",
            "properties": {
                "ai_agent_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_message_at": {
                    "type": "string"
                },
                "message_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_response.ConversationWithDetailsResponse": {
            "type": "object",
            "properties": {
                "ai_agent_avatar": {
                    "type": "string"
                },
                "ai_agent_id": {
                    "type": "string"
                },
                "ai_agent_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_message": {
                    "$ref": "#/definitions/backend-go_internal_handler_http_response.MessageResponse"
                },
                "message_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_response.ConversationsListResponse": {
            "type": "object",
            "properties": {
                "conversations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend-go_internal_handler_http_response.ConversationWithDetailsResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "backend-go_internal_handler_http_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_response.MessageResponse": {
            "type": "object",
            "properties": {
                "ai_session_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "conversation_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sender_id": {
                    "type": "string"
                },
                "sender_type": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_response.MessagesResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend-go_internal_handler_http_response.MessageResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "backend-go_internal_handler_http_response.SendMessageResponse": {
            "type": "object",
            "properties": {
                "ai_message": {
                    "$ref": "#/definitions/backend-go_internal_handler_http_response.MessageResponse"
                },
                "metadata": {},
                "user_message": {
                    "$ref": "#/definitions/backend-go_internal_handler_http_response.MessageResponse"
                }
            }
        },
        "backend-go_internal_handler_http_response.UserResponse": {
            "type": "object",
            "properties": {
                "cognito_user_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "backend-go_internal_handler_http_response.UsersResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/backend-go_internal_handler_http_response.UserResponse"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "BridgeSpeak API",
	Description:      "BridgeSpeak AI分身チャットアプリケーションのAPI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
